Traceback (most recent call last):
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/_parsers/hiredis.py", line 130, in read_response
    self.read_from_socket()
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/_parsers/hiredis.py", line 90, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/cicada2313/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 128, in <module>
    main()
  File "/home/cicada2313/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 34, in main
    FrappeCommandGroup(commands=commands)(prog_name="bench")
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 1167, in run
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time) 
   File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 1029, in get_message
            response = self.parse_response(block=(timeout is None), timeout=timeout) 
        ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
^^    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
^^^^    ^return __callback(*args, **kwargs)^
^      ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 840, in parse_response
^^^^^^^^^    
response = self._execute(conn, try_read)  File "/home/cicada2313/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 205, in start_worker

                 start_worker( 
   File "/home/cicada2313/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 314, in start_worker
^^^^^    ^^^worker.work(^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/rq/worker.py", line 458, in work
^^^^^^^^^^^^^^^^^^^
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 816, in _execute
        return conn.retry.call_with_retry(self.teardown()

  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/rq/worker.py", line 1048, in teardown
        self.register_death() 
   File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/rq/worker.py", line 834, in register_death
     ^^^^    ^p.execute()^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 1497, in execute
^^^    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)^^
^  ^ ^ ^ ^ ^ ^ ^ ^  ^^^^^^^^^^^^^^^^^^^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/retry.py", line 65, in call_with_retry
^^^^    ^fail(error)^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 818, in <lambda>
^^^^    ^lambda error: self._disconnect_raise_connect(conn, error),^
^    ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 1074, in get_connection
^    ^^^^connection.connect()^
^  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 289, in connect
^^^^^^^^^^^^^^^^
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 805, in _disconnect_raise_connect
    self.on_connect()
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 391, in on_connect
    raise error    
self.read_response()  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/retry.py", line 62, in call_with_retry
    
return do()  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 520, in read_response

           ^^^^
  File "/home/cicada2313/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 817, in <lambda>
        raise ConnectionError(lambda: command(*args, **kwargs),
 
 redis.exceptions.ConnectionError:    Error while reading from 127.0.0.1:11000 : (104, 'Connection reset by peer')
  